---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chuckyma/
    - /bin/cp -r * $DEPLOYPATH #copy all from root
    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/afterworkchills
    - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/afterworkchills/js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/afterworkchills/css
